# Navbar Menus
[[nav]]
name = "tu-biblioteca"
url = "tu-biblioteca/"
weight = 1

[[nav]]
name = "recursos"
url = "recursos/"
weight = 2

[[nav]]
name = "soy-estudiante"
url = "soy-estudiante/"
weight = 3

[[nav]]
name = "soy-pdi"
url = "soy-pdi/"
weight = 4

[[nav]]
name = "buscar"
url = "buscar/"
weight = 5

# Footer acciones Menu
[[acciones]]
name = "graphicdesign"
url = "acciones/"
weight = 1
[[acciones]]
name = "webdesign"
url = "acciones/"
weight = 2
[[acciones]]
name = "webdevelopment"
url = "acciones/"
weight = 3

# Footer Quick links Menu
[[quicklink]]
name = "partners"
url = "ofilibre/"
weight = 1
[[quicklink]]
name = "ofilibre"
url = "ofilibre/"
weight = 2
[[quicklink]]
name = "faqs"
url = "ofilibre/"
weight = 3
[[quicklink]]
name = "badges"
url = "ofilibre/"
weight = 4
